"use client";

import { FormEvent, useMemo, useState } from "react";

type Package = { id: number; name: string; occasion: string; price: number; image: string; description: string; includes: string[]; badge?: string };
type Extra = { id: string; name: string; price: number; icon: string };

const packages: Package[] = [
  { id: 1, name: "Despierta bonito", occasion: "Cumpleaños", price: 589, image: "/package-sunrise.png", description: "Un desayuno luminoso, fresco y muy apapachador.", includes: ["Hot cakes con fruta", "Huevito y tocino", "Café + jugo", "Mini ramo", "Tarjeta personalizada"], badge: "Más elegido" },
  { id: 2, name: "Mañana contigo", occasion: "Romántico", price: 699, image: "/package-romance.png", description: "Para decir mucho antes de que empiece el día.", includes: ["Croissant artesanal", "Mini waffles", "Café + jugo", "Flores", "Globo y dedicatoria"], badge: "Nuevo" },
  { id: 3, name: "Brunch sin prisa", occasion: "Para compartir", price: 849, image: "/hero-breakfast.png", description: "Una mesa completa para dos y una mañana memorable.", includes: ["Desayuno para 2", "Fruta de temporada", "2 bebidas", "Pan dulce", "Mensaje especial"] },
];

const extras: Extra[] = [
  { id: "balloon", name: "Globo con helio", price: 110, icon: "◇" },
  { id: "flowers", name: "Ramo de flores", price: 190, icon: "✿" },
  { id: "photos", name: "Tira de 4 fotos", price: 75, icon: "▣" },
  { id: "cake", name: "Mini pastel", price: 165, icon: "⌒" },
];

const money = (value: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 }).format(value);

function ArrowIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M5 12h14M14 7l5 5-5 5" /></svg> }
function BagIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M5 8h14l-1 12H6L5 8Z" /><path d="M9 9V6a3 3 0 0 1 6 0v3" /></svg> }
function CheckIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2"><path d="m5 12 4 4L19 6" /></svg> }

export default function Home() {
  const [selected, setSelected] = useState<Package>(packages[0]);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [step, setStep] = useState(1);
  const [selectedExtras, setSelectedExtras] = useState<string[]>([]);
  const [deliveryZone, setDeliveryZone] = useState("centro");
  const [occasion, setOccasion] = useState("Cumpleaños");
  const [recipient, setRecipient] = useState("");
  const [sender, setSender] = useState("");
  const [phone, setPhone] = useState("");
  const [address, setAddress] = useState("");
  const [date, setDate] = useState("");
  const [schedule, setSchedule] = useState("8:00 – 9:30");
  const [message, setMessage] = useState("¡Que hoy te pasen cosas bonitas!");
  const [notes, setNotes] = useState("");
  const [payment, setPayment] = useState("card");
  const [confirmed, setConfirmed] = useState(false);
  const extrasTotal = useMemo(() => extras.filter(e => selectedExtras.includes(e.id)).reduce((sum, e) => sum + e.price, 0), [selectedExtras]);
  const delivery = deliveryZone === "centro" ? 59 : 89;
  const total = selected.price + extrasTotal + delivery;
  const minDate = "2026-08-26";

  const openBuilder = (pkg: Package) => { setSelected(pkg); setStep(1); setConfirmed(false); setDrawerOpen(true) };
  const toggleExtra = (id: string) => setSelectedExtras(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const nextStep = (event?: FormEvent) => { event?.preventDefault(); setStep(current => Math.min(current + 1, 4)) };

  return (
    <main className="min-h-screen overflow-hidden bg-[#f8f2e9] text-[#321c19]">
      <header className="fixed inset-x-0 top-0 z-40 border-b border-[#6f0b0b]/10 bg-[#f8f2e9]/90 backdrop-blur-xl">
        <div className="mx-auto flex h-[78px] max-w-[1440px] items-center justify-between px-5 md:px-10">
          <a href="#inicio" className="flex items-center gap-3" aria-label="Mañana Rica, inicio">
            <img src="/manana-rica-logo.png" alt="" className="h-14 w-14 object-contain" />
            <div className="leading-none"><span className="block font-serif text-xl font-semibold tracking-tight text-[#780d0b]">Mañana Rica</span><span className="mt-1 block text-[9px] font-semibold uppercase tracking-[0.24em] text-[#8f5f43]">Sorpresas que despiertan</span></div>
          </a>
          <nav className="hidden items-center gap-8 text-sm font-medium md:flex" aria-label="Navegación principal"><a href="#paquetes" className="transition hover:text-[#8a0f0d]">Paquetes</a><a href="#como-funciona" className="transition hover:text-[#8a0f0d]">Cómo funciona</a><a href="#faq" className="transition hover:text-[#8a0f0d]">Preguntas</a></nav>
          <button onClick={() => openBuilder(selected)} className="group flex items-center gap-2 border border-[#780d0b] px-4 py-2.5 text-sm font-semibold text-[#780d0b] transition hover:bg-[#780d0b] hover:text-white"><BagIcon /><span className="hidden sm:inline">Armar pedido</span></button>
        </div>
      </header>

      <section id="inicio" className="relative mx-auto grid min-h-[760px] max-w-[1440px] items-center gap-8 px-5 pb-16 pt-32 md:px-10 lg:grid-cols-[0.86fr_1.14fr] lg:pt-24">
        <div className="relative z-10 py-10 lg:py-24">
          <p className="mb-7 flex items-center gap-3 text-[11px] font-bold uppercase tracking-[0.25em] text-[#8a0f0d]"><span className="h-px w-10 bg-[#8a0f0d]" /> Entregas en Morelia</p>
          <h1 className="max-w-2xl font-serif text-[clamp(3.8rem,7vw,7.4rem)] leading-[0.84] tracking-[-0.055em] text-[#64100e]">Que su día<br />empiece <em className="font-normal text-[#d96a28]">rico.</em></h1>
          <p className="mt-8 max-w-lg text-base leading-7 text-[#70534b] md:text-lg">Desayunos sorpresa que puedes hacer tan únicos como esa persona. Elige, personaliza y agenda en unos minutos.</p>
          <div className="mt-9 flex flex-wrap items-center gap-4"><button onClick={() => document.getElementById("paquetes")?.scrollIntoView({ behavior: "smooth" })} className="group flex items-center gap-3 bg-[#780d0b] px-6 py-4 text-sm font-bold text-white transition hover:bg-[#951a16]">Ver desayunos <ArrowIcon /></button><span className="text-xs leading-5 text-[#8f7268]">Agenda con 24 h de anticipación<br />Pago seguro · Confirmación inmediata</span></div>
        </div>
        <div className="relative min-h-[460px] lg:min-h-[660px]">
          <div className="absolute inset-0 overflow-hidden rounded-[48%_48%_8%_48%/38%_40%_8%_38%] bg-[#e4c6a1]"><img src="/hero-breakfast.png" alt="Desayuno sorpresa Mañana Rica con hot cakes, fruta, café y flores" className="h-full w-full object-cover" /></div>
          <div className="absolute -bottom-5 left-2 bg-[#fffaf3] p-4 shadow-[0_18px_50px_rgba(74,31,20,.15)] md:left-[-28px] md:p-5"><p className="text-[10px] font-bold uppercase tracking-[0.19em] text-[#b25b2b]">Hecho esta mañana</p><p className="mt-1 font-serif text-2xl text-[#64100e]">fresco, bonito, para ti.</p></div>
          <div className="absolute right-4 top-8 grid h-24 w-24 rotate-6 place-items-center rounded-full bg-[#f2c44c] text-center text-[10px] font-bold uppercase leading-4 tracking-[0.13em] text-[#64100e] shadow-lg md:h-28 md:w-28"><span>Entrega<br />con amor<br />♡</span></div>
        </div>
      </section>

      <section className="border-y border-[#780d0b]/10 bg-[#780d0b] py-4 text-[#fff4e6]"><div className="marquee-track flex min-w-max items-center gap-12 text-xs font-semibold uppercase tracking-[0.22em]">{["Ingredientes frescos", "Personalizable", "Entrega local", "Hecho en Morelia", "Ingredientes frescos", "Personalizable", "Entrega local", "Hecho en Morelia"].map((text, i) => <span key={i} className="flex items-center gap-12">{text}<b className="text-[#f2c44c]">✦</b></span>)}</div></section>

      <section id="paquetes" className="mx-auto max-w-[1440px] px-5 py-24 md:px-10 md:py-32">
        <div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="eyebrow">La carta de la mañana</p><h2 className="section-title">Elige el antojo.<br /><em>Nosotros ponemos la magia.</em></h2></div><p className="max-w-sm text-sm leading-6 text-[#785c53]">Cada paquete incluye presentación especial y una dedicatoria. Puedes cambiar alimentos y sumar extras durante tu pedido.</p></div>
        <div className="mt-14 grid gap-6 lg:grid-cols-3">
          {packages.map((pkg, index) => <article key={pkg.id} className={`product-card group ${index === 1 ? "lg:translate-y-10" : ""}`}>
            <div className="relative aspect-[4/4.35] overflow-hidden bg-[#e7d7c4]"><img src={pkg.image} alt={pkg.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.035]" />{pkg.badge && <span className="absolute left-4 top-4 bg-[#f8f2e9] px-3 py-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#780d0b]">{pkg.badge}</span>}<button onClick={() => openBuilder(pkg)} className="absolute bottom-4 right-4 grid h-12 w-12 place-items-center rounded-full bg-[#780d0b] text-white transition group-hover:rotate-[-12deg] group-hover:bg-[#d96a28]" aria-label={`Personalizar ${pkg.name}`}><ArrowIcon /></button></div>
            <div className="border-x border-b border-[#780d0b]/15 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#b25b2b]">{pkg.occasion}</p><h3 className="mt-2 font-serif text-2xl text-[#55100e]">{pkg.name}</h3></div><p className="whitespace-nowrap font-serif text-xl text-[#780d0b]">{money(pkg.price)}</p></div><p className="mt-3 text-sm leading-6 text-[#785c53]">{pkg.description}</p></div>
          </article>)}
        </div>
      </section>

      <section id="como-funciona" className="bg-[#eadac7] px-5 py-24 md:px-10 md:py-28"><div className="mx-auto max-w-[1440px]"><p className="eyebrow">Así de sencillo</p><div className="mt-3 grid gap-10 lg:grid-cols-[0.7fr_1.3fr]"><h2 className="section-title">De tu idea<br /><em>a su puerta.</em></h2><div className="grid border-t border-[#780d0b]/20 sm:grid-cols-3">{[["01", "Elige", "Encuentra el paquete que más se parece a esa persona."], ["02", "Hazlo suyo", "Personaliza sabores, mensaje, ocasión y todos los extras."], ["03", "Agenda", "Indica dónde y cuándo. Nosotros preparamos y entregamos."]].map(([number, title, copy]) => <div key={number} className="border-b border-[#780d0b]/20 py-7 sm:border-r sm:px-6 sm:last:border-r-0"><span className="font-serif text-sm text-[#b25b2b]">{number}</span><h3 className="mt-10 font-serif text-2xl text-[#64100e]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#785c53]">{copy}</p></div>)}</div></div></div></section>

      <section className="mx-auto max-w-[1440px] px-5 py-24 md:px-10 md:py-32"><div className="grid overflow-hidden bg-[#64100e] text-[#fff8ef] lg:grid-cols-[1.1fr_.9fr]"><div className="p-8 md:p-14 lg:p-20"><p className="text-[11px] font-bold uppercase tracking-[0.23em] text-[#f2c44c]">Un detalle importante</p><h2 className="mt-5 max-w-2xl font-serif text-4xl leading-[1.04] md:text-6xl">No enviamos solo desayuno. Enviamos ese “pensé en ti”.</h2><button onClick={() => openBuilder(packages[0])} className="mt-9 flex items-center gap-3 bg-[#f2c44c] px-6 py-4 text-sm font-bold text-[#64100e] transition hover:bg-white">Armar una sorpresa <ArrowIcon /></button></div><div className="relative min-h-80"><img src="/package-romance.png" alt="Paquete romántico de desayuno sorpresa" className="absolute inset-0 h-full w-full object-cover" /></div></div></section>

      <section id="faq" className="mx-auto grid max-w-[1160px] gap-10 px-5 pb-28 md:grid-cols-[.7fr_1.3fr] md:px-10"><div><p className="eyebrow">Antes de ordenar</p><h2 className="mt-3 font-serif text-4xl text-[#64100e] md:text-5xl">Lo bueno se planea.</h2></div><div className="divide-y divide-[#780d0b]/15 border-y border-[#780d0b]/15">{[["¿Con cuánto tiempo debo pedir?", "Recomendamos al menos 24 horas de anticipación. Para pedidos del mismo día, consulta disponibilidad por WhatsApp."], ["¿Entregan en todo Morelia?", "Sí, cubrimos Morelia y zonas cercanas. El costo se calcula según la zona elegida al comprar."], ["¿Puedo cambiar alimentos?", "Claro. Puedes indicarnos alergias o preferencias; confirmaremos contigo cualquier ajuste especial."]].map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-serif text-xl text-[#64100e]">{question}<span className="text-2xl font-light transition group-open:rotate-45">+</span></summary><p className="max-w-xl pt-4 text-sm leading-6 text-[#785c53]">{answer}</p></details>)}</div></section>

      <footer className="bg-[#2f1714] px-5 py-12 text-[#f8f2e9] md:px-10"><div className="mx-auto grid max-w-[1440px] gap-10 md:grid-cols-[1fr_auto_auto] md:items-end"><div className="flex items-center gap-3"><img src="/manana-rica-logo.png" alt="" className="h-14 w-14 object-contain" /><div><p className="font-serif text-2xl">Mañana Rica</p><p className="text-xs text-[#d9bca9]">Desayunos sorpresa · Morelia, Mich.</p></div></div><div className="text-sm leading-7 text-[#d9bca9]"><p>Lunes a sábado · 8:00–18:00</p><p>Pedidos con 24 h de anticipación</p></div><a href="https://wa.me/524431234567" className="flex items-center gap-2 text-sm font-semibold text-[#f2c44c]" target="_blank" rel="noreferrer">Hablar por WhatsApp <ArrowIcon /></a></div><div className="mx-auto mt-10 flex max-w-[1440px] justify-between border-t border-white/10 pt-5 text-[11px] text-[#a88d82]"><span>© 2026 Mañana Rica</span><span>Demo de tienda · Morelia</span></div></footer>

      {drawerOpen && <div className="fixed inset-0 z-50 flex justify-end bg-[#2b1410]/55 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Personalizar pedido">
        <button className="absolute inset-0 cursor-default" onClick={() => setDrawerOpen(false)} aria-label="Cerrar personalizador" />
        <aside className="relative h-full w-full overflow-y-auto bg-[#fffaf3] shadow-2xl md:w-[min(760px,92vw)]">
          <div className="sticky top-0 z-10 border-b border-[#780d0b]/10 bg-[#fffaf3]/95 px-5 py-5 backdrop-blur md:px-9"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#b25b2b]">Tu sorpresa</p><h2 className="mt-1 font-serif text-2xl text-[#64100e]">{confirmed ? "Pedido confirmado" : selected.name}</h2></div><button onClick={() => setDrawerOpen(false)} className="grid h-10 w-10 place-items-center rounded-full border border-[#780d0b]/15 text-xl text-[#64100e]" aria-label="Cerrar">×</button></div>{!confirmed && <div className="mt-5 grid grid-cols-4 gap-2" aria-label={`Paso ${step} de 4`}>{[1,2,3,4].map(item => <span key={item} className={`h-1 ${item <= step ? "bg-[#d96a28]" : "bg-[#e8d9ca]"}`} />)}</div>}</div>
          <div className="px-5 py-7 md:px-9 md:py-9">
            {step === 1 && <div><p className="step-label">Paso 1 · Personaliza</p><h3 className="step-title">Hazlo muy de esa persona.</h3><div className="mt-7 grid gap-3 sm:grid-cols-2">{extras.map(extra => { const active = selectedExtras.includes(extra.id); return <button key={extra.id} onClick={() => toggleExtra(extra.id)} className={`flex items-center gap-4 border p-4 text-left transition ${active ? "border-[#780d0b] bg-[#f8eee1]" : "border-[#d8c7b7] hover:border-[#b9896e]"}`} aria-pressed={active}><span className={`grid h-11 w-11 place-items-center rounded-full text-xl ${active ? "bg-[#780d0b] text-white" : "bg-[#eadac7] text-[#780d0b]"}`}>{active ? <CheckIcon /> : extra.icon}</span><span className="flex-1"><b className="block text-sm">{extra.name}</b><small className="text-[#8a6b60]">+ {money(extra.price)}</small></span></button> })}</div><label className="mt-7 block text-xs font-bold uppercase tracking-[.13em] text-[#79564c]">Ocasión</label><div className="mt-3 flex flex-wrap gap-2">{["Cumpleaños", "Amor", "Gracias", "Solo porque sí"].map(item => <button key={item} onClick={() => setOccasion(item)} className={`px-4 py-2 text-sm ${occasion === item ? "bg-[#780d0b] text-white" : "border border-[#d8c7b7]"}`}>{item}</button>)}</div><div className="mt-8 border-t border-[#780d0b]/10 pt-6"><p className="summary-label">Este paquete incluye</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{selected.includes.map(item => <span key={item} className="flex items-center gap-2 text-sm text-[#68483f]"><CheckIcon />{item}</span>)}</div></div></div>}
            {step === 2 && <form id="recipient-form" onSubmit={nextStep}><p className="step-label">Paso 2 · Dedicatoria</p><h3 className="step-title">¿Quién recibirá el apapacho?</h3><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="field">Nombre de quien recibe<input required value={recipient} onChange={e => setRecipient(e.target.value)} placeholder="Ej. Sofía" /></label><label className="field">Tu nombre<input required value={sender} onChange={e => setSender(e.target.value)} placeholder="Ej. Brenda" /></label></div><label className="field mt-5">Mensaje para la tarjeta<textarea required maxLength={180} rows={4} value={message} onChange={e => setMessage(e.target.value)} /><small>{message.length}/180</small></label><label className="field mt-5">Alergias o indicaciones especiales <span>(opcional)</span><textarea rows={2} value={notes} onChange={e => setNotes(e.target.value)} placeholder="Sin nueces, leche deslactosada…" /></label></form>}
            {step === 3 && <form id="delivery-form" onSubmit={nextStep}><p className="step-label">Paso 3 · Entrega</p><h3 className="step-title">Dinos dónde y cuándo.</h3><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="field">Fecha<input required type="date" min={minDate} value={date} onChange={e => setDate(e.target.value)} /></label><label className="field">Horario<select value={schedule} onChange={e => setSchedule(e.target.value)}><option>8:00 – 9:30</option><option>9:30 – 11:00</option><option>11:00 – 12:30</option></select></label><label className="field sm:col-span-2">Dirección de entrega<textarea required rows={2} value={address} onChange={e => setAddress(e.target.value)} placeholder="Calle, número, colonia y referencias" /></label><label className="field">Teléfono de contacto<input required inputMode="tel" value={phone} onChange={e => setPhone(e.target.value)} placeholder="443 000 0000" /></label><label className="field">Zona<select value={deliveryZone} onChange={e => setDeliveryZone(e.target.value)}><option value="centro">Morelia centro · $59</option><option value="extendida">Zona extendida · $89</option></select></label></div><div className="mt-6 border-l-2 border-[#d96a28] bg-[#f8eee1] p-4 text-xs leading-5 text-[#785c53]">La hora es una ventana estimada. Te avisaremos por WhatsApp cuando el pedido salga a ruta.</div></form>}
            {step === 4 && <div><p className="step-label">Paso 4 · Revisa y paga</p><h3 className="step-title">Todo listo para alegrar su mañana.</h3><div className="mt-7 flex gap-4 border-b border-[#780d0b]/10 pb-6"><img src={selected.image} alt="" className="h-24 w-24 object-cover" /><div className="flex-1"><h4 className="font-serif text-xl text-[#64100e]">{selected.name}</h4><p className="mt-1 text-xs text-[#785c53]">{occasion} · {recipient || "Destinatario"}</p><p className="mt-3 text-sm font-bold">{money(selected.price)}</p></div></div>{selectedExtras.length > 0 && <div className="border-b border-[#780d0b]/10 py-5"><p className="summary-label">Extras</p>{extras.filter(e => selectedExtras.includes(e.id)).map(e => <div key={e.id} className="mt-2 flex justify-between text-sm"><span>{e.name}</span><span>{money(e.price)}</span></div>)}</div>}<div className="grid gap-4 border-b border-[#780d0b]/10 py-5 text-sm sm:grid-cols-2"><div><p className="summary-label">Entrega</p><p className="mt-2">{date || "Fecha por definir"}<br />{schedule}</p></div><div><p className="summary-label">Dirección</p><p className="mt-2 line-clamp-2">{address || "Dirección por definir"}</p></div></div><p className="summary-label mt-6">Método de pago · simulación</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><button onClick={() => setPayment("card")} className={`border p-4 text-left text-sm ${payment === "card" ? "border-[#780d0b] bg-[#f8eee1]" : "border-[#d8c7b7]"}`}><b>Tarjeta demo</b><small className="mt-1 block text-[#8a6b60]">Visa •••• 4242</small></button><button onClick={() => setPayment("transfer")} className={`border p-4 text-left text-sm ${payment === "transfer" ? "border-[#780d0b] bg-[#f8eee1]" : "border-[#d8c7b7]"}`}><b>Transferencia</b><small className="mt-1 block text-[#8a6b60]">Datos al confirmar</small></button></div><div className="mt-6 flex items-center justify-between border-y border-[#780d0b]/15 py-5"><span className="font-serif text-xl">Total</span><strong className="font-serif text-3xl text-[#780d0b]">{money(total)}</strong></div></div>}
            {step === 5 && confirmed && <div className="py-5 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#f2c44c] text-[#64100e]"><CheckIcon /></div><p className="step-label mt-7">Pedido MR-260825-014</p><h3 className="mt-3 font-serif text-4xl text-[#64100e]">¡La sorpresa ya está en marcha!</h3><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-[#785c53]">Esta es una confirmación demo. En la tienda real enviaremos el comprobante y las actualizaciones de entrega a tu WhatsApp.</p><div className="mx-auto mt-8 max-w-md border border-[#d8c7b7] p-5 text-left text-sm"><div className="flex justify-between"><span>{selected.name}</span><b>{money(total)}</b></div><div className="mt-3 flex justify-between text-[#785c53]"><span>{date || "Fecha por definir"}</span><span>{schedule}</span></div></div><a href="https://wa.me/524431234567?text=Hola%20Mañana%20Rica%2C%20quiero%20dar%20seguimiento%20al%20pedido%20MR-260825-014" target="_blank" rel="noreferrer" className="mx-auto mt-6 flex w-fit items-center gap-3 bg-[#780d0b] px-6 py-4 text-sm font-bold text-white">Dar seguimiento por WhatsApp <ArrowIcon /></a><button onClick={() => setDrawerOpen(false)} className="mt-5 block w-full text-sm font-semibold text-[#780d0b] underline underline-offset-4">Volver a la tienda</button></div>}
          </div>
          {!confirmed && <div className="sticky bottom-0 border-t border-[#780d0b]/10 bg-[#fffaf3] px-5 py-5 shadow-[0_-12px_35px_rgba(74,31,20,.08)] md:px-9"><div className="mb-4 flex items-center justify-between text-sm"><span className="text-[#785c53]">Total estimado</span><strong className="font-serif text-2xl text-[#64100e]">{money(total)}</strong></div><div className="flex gap-3">{step > 1 && <button onClick={() => setStep(step - 1)} className="border border-[#780d0b]/25 px-5 py-3.5 text-sm font-bold text-[#64100e]">Atrás</button>}{step < 4 ? <button type="submit" form={step === 2 ? "recipient-form" : step === 3 ? "delivery-form" : undefined} onClick={step === 1 ? () => nextStep() : undefined} className="flex flex-1 items-center justify-center gap-3 bg-[#780d0b] px-6 py-3.5 text-sm font-bold text-white">Continuar <ArrowIcon /></button> : <button onClick={() => { setConfirmed(true); setStep(5) }} className="flex flex-1 items-center justify-center gap-3 bg-[#d96a28] px-6 py-3.5 text-sm font-bold text-white">Confirmar pedido demo <ArrowIcon /></button>}</div></div>}
        </aside>
      </div>}
    </main>
  );
}
